import type {
  Booking,
  Conversation,
  GuestProfile,
  IoTDevice,
  NewsletterSubscriber,
  PortalWidget,
  TaskItem,
  Template,
} from './types';

export const guestProfiles: GuestProfile[] = [
  {
    id: 'guest-giovanni-greco',
    name: 'Giovanni Greco',
    email: 'giovanni.greco@example.com',
    phone: '+39 320 456 7821',
    lastInteraction: '2025-02-16T09:45:00Z',
    lastStay: '2024-12-12',
    tags: ['Family friendly', 'Spa lover', 'Early check-in'],
    loyaltyTier: 'Gold',
    newsletter: true,
    preferences: [
      {
        id: 'pref-spa',
        label: 'Accesso spa serale',
        icon: 'sparkles',
        notes: 'Gradisce prosecco freddo in cabina privata',
      },
      {
        id: 'pref-room',
        label: 'Piano alto vista mare',
        icon: 'waves',
      },
      {
        id: 'pref-food',
        label: 'Colazione senza lattosio',
        icon: 'leaf',
      },
    ],
    notes: [
      {
        id: 'note-1',
        createdAt: '2025-02-16T09:50:00Z',
        author: 'AI Concierge',
        sentiment: 'positivo',
        content:
          'Ha espresso entusiasmo per la nuova suite Luna. Suggerita email di follow-up per upsell pacchetto spa.',
      },
      {
        id: 'note-2',
        createdAt: '2024-12-10T18:30:00Z',
        author: 'Reception',
        sentiment: 'neutro',
        content: 'Preferisce contatti via WhatsApp durante il soggiorno.',
      },
    ],
    upcomingStay: '2025-03-05',
    automationHealth: 92,
    averageSpend: 1280,
    favouriteRoom: 'Suite Luna 804',
  },
  {
    id: 'guest-francesca-gallo',
    name: 'Francesca Gallo',
    email: 'francesca.gallo@example.com',
    phone: '+39 339 112 9044',
    lastInteraction: '2025-02-15T15:22:00Z',
    lastStay: '2024-10-18',
    tags: ['Wellness', 'Digital Nomad'],
    loyaltyTier: 'Platinum',
    newsletter: false,
    preferences: [
      {
        id: 'pref-workspace',
        label: 'Scrivania ergonomica',
        icon: 'briefcase',
      },
      {
        id: 'pref-food',
        label: 'Colazione vegana',
        icon: 'leaf',
        notes: 'Ama centrifughe con zenzero e menta',
      },
    ],
    notes: [
      {
        id: 'note-3',
        createdAt: '2025-02-15T15:30:00Z',
        author: 'AI Concierge',
        sentiment: 'positivo',
        content: 'Suggerire pacchetto detox 3 giorni + massaggio olistico.',
      },
    ],
    upcomingStay: '2025-02-28',
    automationHealth: 88,
    averageSpend: 970,
  },
  {
    id: 'guest-antonio-marino',
    name: 'Antonio Marino',
    email: 'antonio.marino@example.com',
    phone: '+39 347 226 7801',
    lastInteraction: '2025-02-14T11:10:00Z',
    lastStay: '2024-07-04',
    tags: ['Business', 'Golf'],
    loyaltyTier: 'Silver',
    newsletter: true,
    preferences: [
      {
        id: 'pref-golf',
        label: 'Transfer mattutino al golf club',
        icon: 'flag',
      },
      {
        id: 'pref-room',
        label: 'Cuscino memory foam',
        icon: 'moon',
      },
    ],
    notes: [
      {
        id: 'note-4',
        createdAt: '2025-02-13T10:00:00Z',
        author: 'Concierge',
        sentiment: 'positivo',
        content: 'Apprezza comunicazioni concise. Predilige pagamento anticipato.',
      },
    ],
    automationHealth: 75,
    averageSpend: 640,
  },
];

export const iotDevices: IoTDevice[] = [
  {
    id: 'iot-suite-luna',
    type: 'clima',
    name: 'Climatizzazione Suite Luna',
    status: 'online',
    metrics: [
      { label: 'Temperatura', value: '21.5°C', trend: 'down' },
      { label: 'Qualità aria', value: 'Ottima', trend: 'up' },
    ],
    lastSync: '2025-02-16T10:05:00Z',
    room: 'Suite Luna 804',
  },
  {
    id: 'iot-frigobar-804',
    type: 'frigobar',
    name: 'Frigobar Suite Luna',
    status: 'warning',
    metrics: [
      { label: 'Champagne', value: '1 bottiglia', trend: 'down' },
      { label: 'Snack gourmet', value: '2 porzioni', trend: 'down' },
    ],
    lastSync: '2025-02-16T09:55:00Z',
    room: 'Suite Luna 804',
  },
  {
    id: 'iot-spa-privata',
    type: 'wellness',
    name: 'Spa privata camera 512',
    status: 'online',
    metrics: [
      { label: 'Temperatura vasca', value: '37°C', trend: 'stable' },
      { label: 'Diffusore essenze', value: 'Lavanda', trend: 'stable' },
    ],
    lastSync: '2025-02-16T09:40:00Z',
    room: 'Suite Aurora 512',
  },
  {
    id: 'iot-luce-rooftop',
    type: 'illuminazione',
    name: 'Illuminazione Rooftop Bar',
    status: 'offline',
    metrics: [
      { label: 'Stato circuito', value: 'In manutenzione' },
    ],
    lastSync: '2025-02-16T07:12:00Z',
  },
];

export const bookings: Booking[] = [
  {
    id: 'booking-001',
    code: 'CA-2025-001',
    guestId: 'guest-giovanni-greco',
    channel: 'booking',
    type: 'proposta',
    roomType: 'Suite Luna con Spa',
    rooms: 2,
    guests: 4,
    checkIn: '2025-03-05',
    checkOut: '2025-03-10',
    status: 'proposta',
    total: 3420,
    currency: 'EUR',
    nextAction: 'Conferma proposta con upgrade spa',
    aiConfidence: 0.82,
    automations: [
      {
        id: 'auto-1',
        title: 'Proposta inviata',
        description: 'Email personalizzata con tre opzioni di suite e benefits spa inclusi',
        scheduledAt: '2025-02-16T09:45:00Z',
        status: 'completato',
        channel: 'email',
        aiSuggestedCopy:
          'Ciao Giovanni, abbiamo riservato per la tua famiglia la Suite Luna con area wellness privata. In allegato trovi tre proposte su misura per il tuo soggiorno.',
      },
      {
        id: 'auto-2',
        title: 'Promemoria WhatsApp',
        description: 'Richiesta feedback entro 24h con suggerimento AI',
        scheduledAt: '2025-02-17T09:45:00Z',
        status: 'in_attesa',
        channel: 'whatsapp',
        aiSuggestedCopy:
          'Ciao Giovanni! Posso aiutarti a scegliere la suite ideale? Posso mostrarti i dettagli della Luna con Spa privata, perfetta per le tue richieste.',
        guardrails: [
          'Se l’ospite chiede informazioni sui prezzi, confermare solo quelli presenti in proposta',
          'Escalare all’operatore se viene richiesto un servizio non incluso',
        ],
      },
      {
        id: 'auto-3',
        title: 'Richiesta pagamento online',
        description: 'Invio link pagamento con condizioni flessibili',
        scheduledAt: '2025-02-19T08:00:00Z',
        status: 'in_attesa',
        channel: 'email',
      },
    ],
    iotDevices: iotDevices.filter((device) => device.room === 'Suite Luna 804'),
    externalLinks: [
      { label: 'Prenotazione Booking.com', href: 'https://booking.com/reservation/CA-2025-001' },
      { label: 'Cartella Cliente', href: '/clients/guest-giovanni-greco' },
    ],
  },
  {
    id: 'booking-002',
    code: 'CA-2025-002',
    guestId: 'guest-francesca-gallo',
    channel: 'direct',
    type: 'diretta',
    roomType: 'Suite Aurora Rooftop',
    rooms: 1,
    guests: 2,
    checkIn: '2025-02-28',
    checkOut: '2025-03-04',
    status: 'in_attesa_pagamento',
    total: 1980,
    currency: 'EUR',
    nextAction: 'Invio promemoria pagamento 50% acconto',
    aiConfidence: 0.74,
    automations: [
      {
        id: 'auto-4',
        title: 'Conferma prenotazione',
        description: 'Email riepilogo servizi e suggerimenti digital nomad',
        scheduledAt: '2025-02-15T16:00:00Z',
        status: 'completato',
        channel: 'email',
      },
      {
        id: 'auto-5',
        title: 'Suggerimento menu detox',
        description: 'Messaggio AI con scelta di centrifughe',
        scheduledAt: '2025-02-26T11:00:00Z',
        status: 'in_attesa',
        channel: 'whatsapp',
      },
    ],
    iotDevices: [iotDevices[2]],
  },
  {
    id: 'booking-003',
    code: 'CA-2025-003',
    guestId: 'guest-antonio-marino',
    channel: 'direct',
    type: 'manuale',
    roomType: 'Executive vista campo golf',
    rooms: 1,
    guests: 1,
    checkIn: '2025-03-18',
    checkOut: '2025-03-20',
    status: 'in_corso',
    total: 880,
    currency: 'EUR',
    nextAction: 'Invia questionario preferenze tee-time',
    aiConfidence: 0.66,
    automations: [
      {
        id: 'auto-6',
        title: 'Promemoria arrivo',
        description: 'SMS con istruzioni parcheggio e codice camera',
        scheduledAt: '2025-03-17T18:00:00Z',
        status: 'in_attesa',
        channel: 'phone',
      },
      {
        id: 'auto-7',
        title: 'Nota concierge',
        description: 'AI suggerisce upgrade driver privato',
        scheduledAt: '2025-03-17T10:00:00Z',
        status: 'in_corso',
        channel: 'email',
      },
    ],
    iotDevices: [],
  },
];

export const conversations: Conversation[] = [
  {
    id: 'conv-001',
    guestId: 'guest-giovanni-greco',
    guestName: 'Giovanni Greco',
    channel: 'whatsapp',
    unread: 2,
    lastMessageAt: '2025-02-16T09:55:00Z',
    status: 'in_gestione',
    aiReadiness: 0.78,
    messages: [
      {
        id: 'msg-1',
        author: 'ospite',
        channel: 'whatsapp',
        content: 'Ciao! Possiamo aggiungere un massaggio di coppia durante il soggiorno?',
        sentAt: '2025-02-16T09:50:00Z',
        sentiment: 'positivo',
      },
      {
        id: 'msg-2',
        author: 'ai',
        channel: 'whatsapp',
        content: 'Certamente! Sto verificando la disponibilità migliore per voi e vi aggiorno tra pochi minuti.',
        sentAt: '2025-02-16T09:51:00Z',
        sentiment: 'positivo',
      },
      {
        id: 'msg-3',
        author: 'ospite',
        channel: 'whatsapp',
        content: 'Perfetto, grazie mille!',
        sentAt: '2025-02-16T09:55:00Z',
      },
    ],
  },
  {
    id: 'conv-002',
    guestId: 'guest-francesca-gallo',
    guestName: 'Francesca Gallo',
    channel: 'email',
    unread: 0,
    lastMessageAt: '2025-02-15T15:20:00Z',
    status: 'risolta',
    aiReadiness: 0.92,
    messages: [
      {
        id: 'msg-4',
        author: 'ospite',
        channel: 'email',
        content: 'Vorrei confermare il pacchetto detox e aggiungere un massaggio sonoro.',
        sentAt: '2025-02-15T15:05:00Z',
      },
      {
        id: 'msg-5',
        author: 'hotel',
        channel: 'email',
        content: 'Fantastico! Ho riservato il pacchetto detox e aggiunto il massaggio sonoro per il 2 marzo alle 17:00.',
        sentAt: '2025-02-15T15:20:00Z',
      },
    ],
  },
  {
    id: 'conv-003',
    guestId: 'guest-antonio-marino',
    guestName: 'Antonio Marino',
    channel: 'booking',
    unread: 1,
    lastMessageAt: '2025-02-14T11:10:00Z',
    status: 'in_attesa',
    aiReadiness: 0.54,
    messages: [
      {
        id: 'msg-6',
        author: 'ospite',
        channel: 'booking',
        content: 'Buongiorno, potete confermare il tee-time per il 19 mattina?',
        sentAt: '2025-02-14T11:05:00Z',
      },
    ],
  },
];

export const newsletterSubscribers: NewsletterSubscriber[] = guestProfiles.map((guest) => ({
  guestId: guest.id,
  name: guest.name,
  email: guest.email,
  optIn: guest.newsletter,
  lastUpdate: '2025-02-14T09:00:00Z',
  source: guest.newsletter ? 'Dashboard' : 'Guest Portal',
}));

export const templates: Template[] = [
  {
    id: 'template-1',
    name: 'Email Offerta Hotel',
    category: 'prestay',
    subject: 'La tua esperienza su misura al Customer Automator',
    description:
      'Proposta di soggiorno personalizzata con focus su benessere famigliare e servizi su misura.',
    updatedAt: '2025-02-10T10:15:00Z',
    aiTone: 'emozionale',
    blocks: [
      {
        id: 'block-1',
        label: 'Saluto personalizzato',
        type: 'variabile',
        content: '{{ospite.nome}}',
      },
      {
        id: 'block-2',
        label: 'Opzioni camere',
        type: 'loop',
        content: '{% for camera in proposte %} ... {% endfor %}',
      },
      {
        id: 'block-3',
        label: 'Call to action',
        type: 'testo',
        content: 'Conferma entro 48h per garantirti il pacchetto esclusivo.',
      },
    ],
  },
  {
    id: 'template-2',
    name: 'Email Conferma Prenotazione',
    category: 'prestay',
    subject: 'La tua prenotazione è confermata — preparati a rilassarti',
    description: 'Riepilogo servizi, link al portale ospite e suggerimenti AI per upselling.',
    updatedAt: '2025-02-12T08:45:00Z',
    aiTone: 'professionale',
    blocks: [
      {
        id: 'block-4',
        label: 'Riepilogo soggiorno',
        type: 'variabile',
        content: '{{prenotazione.riepilogo}}',
      },
      {
        id: 'block-5',
        label: 'Servizi inclusi',
        type: 'loop',
        content: '{% for servizio in soggiorno.servizi %} ... {% endfor %}',
      },
    ],
  },
  {
    id: 'template-3',
    name: 'Email Pre Check-in',
    category: 'prestay',
    subject: 'Il tuo arrivo è vicino — personalizza i dettagli',
    description: 'Richiesta informazioni aggiuntive e preferenze per rendere il soggiorno unico.',
    updatedAt: '2025-02-14T12:05:00Z',
    aiTone: 'friendly',
    blocks: [
      {
        id: 'block-6',
        label: 'Modulo preferenze',
        type: 'condizione',
        content: '{% if ospite.preferenze %} ... {% endif %}',
      },
      {
        id: 'block-7',
        label: 'Chat dedicata',
        type: 'testo',
        content: 'Puoi contattarci via chat unificata per qualsiasi esigenza in tempo reale.',
      },
    ],
  },
];

export const tasks: TaskItem[] = [
  {
    id: 'task-1',
    type: 'to-do',
    guestId: 'guest-giovanni-greco',
    bookingId: 'booking-001',
    title: 'Confermare massaggio di coppia',
    description: 'Verificare disponibilità spa privata per il 7 marzo ore 18:00.',
    dueAt: '2025-02-16T17:00:00Z',
    priority: 'alta',
    completed: false,
  },
  {
    id: 'task-2',
    type: 'nota',
    guestId: 'guest-antonio-marino',
    bookingId: 'booking-003',
    title: 'Organizzare tee-time con golf club partner',
    description: 'Preferisce orario 08:30 con transfer dedicato.',
    dueAt: '2025-03-10T10:00:00Z',
    priority: 'media',
    completed: false,
  },
  {
    id: 'task-3',
    type: 'promemoria',
    title: 'Aggiornare pacchetti romantici Primavera',
    description: 'Creare nuova proposta con degustazione rooftop e spa notturna.',
    dueAt: '2025-02-20T09:00:00Z',
    priority: 'media',
    completed: false,
  },
];

export const portalWidgets: PortalWidget[] = [
  {
    id: 'portal-1',
    title: 'Il tuo soggiorno',
    description: 'Controlla check-in, upgrade e richieste speciali in un colpo d’occhio.',
    icon: 'calendar',
    actionLabel: 'Riepilogo',
  },
  {
    id: 'portal-2',
    title: 'Chat Concierge',
    description: 'Scrivici su WhatsApp, email o chat diretta — risponde anche l’AI.',
    icon: 'message-square',
    actionLabel: 'Apri conversazione',
  },
  {
    id: 'portal-3',
    title: 'Servizi extra',
    description: 'Spa, room service, ristorante gourmet: prenota in autonomia.',
    icon: 'sparkles',
    actionLabel: 'Scopri offerte',
  },
  {
    id: 'portal-4',
    title: 'Esplora la destinazione',
    description: 'Itinerari selezionati dall’hotel, eventi e consigli personalizzati.',
    icon: 'map',
    actionLabel: 'Crea il tuo itinerario',
  },
];
