import type {
  Booking,
  Guest,
  InboxMessage,
  NewsletterSubscriber,
  Template,
  GuestPortalSection,
} from './types';

export const guests: Guest[] = [
  {
    id: 'guest-giovanni-greco',
    name: 'Giovanni Greco',
    email: 'giovanni.greco@example.com',
    phone: '+39 349 011 9987',
    vipLevel: 'gold',
    stays: 6,
    lastStay: '12/08/2024',
    upcomingStay: '25/04/2025',
    averageSpend: 940,
    tags: ['wellness', 'famiglia', 'amante-del-vino'],
    preferences: [
      {
        category: 'comfort',
        title: 'Cuscini anallergici',
        details: 'Richiesta standard in tutte le camere',
        icon: 'feather',
      },
      {
        category: 'wellness',
        title: 'Spa privata',
        details: 'Prenotare sempre fascia serale (19:00)',
        icon: 'sparkle',
      },
      {
        category: 'cucina',
        title: 'Dieta mediterranea',
        details: 'Predilige opzioni senza lattosio',
        icon: 'fork-knife',
      },
    ],
    newsletter: true,
    conciergeNotes:
      'Accompagna spesso partner e due figli. Apprezza il contatto umano, preferisce messaggi personalizzati dal direttore.',
    loyaltyScore: 91,
    travelCompanions: ['Maria Greco', 'Luca Greco', 'Giulia Greco'],
    documents: [
      { type: 'Carta d’identità', url: '#' },
      { type: 'Consenso privacy', url: '#' },
    ],
  },
  {
    id: 'guest-antonio-marino',
    name: 'Antonio Marino',
    email: 'antonio.marino@example.com',
    phone: '+39 340 112 7711',
    vipLevel: 'silver',
    stays: 3,
    lastStay: '02/11/2024',
    averageSpend: 620,
    tags: ['business', 'late-checkout'],
    preferences: [
      {
        category: 'comfort',
        title: 'Camera lato silenzioso',
        details: 'Richiede piano alto e insonorizzazione',
        icon: 'moon',
      },
    ],
    newsletter: false,
    conciergeNotes:
      'Travel manager di una società di consulenza. Ama risposte rapide e riepiloghi con punti elenco.',
    loyaltyScore: 72,
    travelCompanions: ['---'],
    documents: [{ type: 'Carta di credito', url: '#' }],
  },
  {
    id: 'guest-francesca-gallo',
    name: 'Francesca Gallo',
    email: 'francesca.gallo@example.com',
    phone: '+39 333 188 2200',
    vipLevel: 'platinum',
    stays: 11,
    lastStay: '21/09/2024',
    upcomingStay: '14/02/2025',
    averageSpend: 1350,
    tags: ['luxury', 'spa', 'gourmet'],
    preferences: [
      {
        category: 'occasioni',
        title: 'Ricorrenze romantiche',
        details: 'Richiede spesso setup con petali di rosa e champagne',
        icon: 'heart',
      },
      {
        category: 'wellness',
        title: 'Trattamenti personalizzati',
        details: 'Gradisce suggerimenti proattivi del concierge digitale',
        icon: 'sparkle',
      },
    ],
    newsletter: true,
    conciergeNotes:
      'Lascia recensioni dettagliate e condivide foto sui social. Invitare alla nuova esperienza “Chef Table”.',
    loyaltyScore: 97,
    travelCompanions: ['Marco Riva'],
    documents: [{ type: 'Passaporto', url: '#' }],
  },
];

export const bookings: Booking[] = [
  {
    id: 'booking-001',
    reference: 'Prenotazione n°1',
    guestId: 'guest-giovanni-greco',
    guestName: 'Giovanni Greco',
    stayPeriod: '25 Apr → 29 Apr 2025',
    nights: 4,
    adults: 2,
    children: 2,
    status: 'attesa_pagamento',
    channel: 'portale',
    packageName: 'Family Relax Suite',
    outstandingBalance: 320,
    aiConfidence: 0.82,
    roomType: 'Suite Aurora',
    aiInsights: [
      'Suggerire upgrade spa per la seconda serata: probabilità di conversione 68%.',
      'Inviare reminder pagamento 24h prima dell’arrivo con link personalizzato.',
    ],
    automation: [
      {
        id: 'step-01',
        label: 'Proposta inviata',
        description: 'Email con riepilogo pacchetti e tariffe',
        channel: 'email',
        status: 'completato',
        scheduledAt: '02/03/2025 09:30',
        completedAt: '02/03/2025 09:31',
      },
      {
        id: 'step-02',
        label: 'Reminder pagamento',
        description: 'WhatsApp con link di pagamento sicuro',
        channel: 'whatsapp',
        status: 'in_attesa',
        scheduledAt: '18/04/2025 18:00',
      },
      {
        id: 'step-03',
        label: 'Welcome kit digitale',
        description: 'Messaggio Booking con credenziali area ospite',
        channel: 'booking',
        status: 'manuale',
        scheduledAt: '24/04/2025 10:00',
      },
      {
        id: 'step-04',
        label: 'Follow-up post check-out',
        description: 'Email con richiesta feedback e sconto loyalty',
        channel: 'email',
        status: 'in_attesa',
        scheduledAt: '02/05/2025 11:00',
      },
    ],
    sensors: [
      {
        id: 'clima-suite-aurora',
        name: 'Clima Suite',
        icon: 'thermometer',
        value: '21.5',
        unit: '°C',
        status: 'ok',
        lastUpdate: '5 min fa',
        actionable: true,
        actions: ['Imposta 22°C', 'Attiva profumazione'],
      },
      {
        id: 'frigobar-suite-aurora',
        name: 'Frigobar',
        icon: 'bottle',
        value: 'Scorte 78%',
        status: 'alert',
        lastUpdate: '2 h fa',
        actionable: true,
        actions: ['Notifica housekeeping', 'Segna come riempito'],
      },
    ],
    tags: ['famiglia', 'upsell-spa', 'digital-concierge'],
    createdAt: '02/03/2025',
    externalReferences: {
      bookingCom: 'https://admin.booking.com/reservations/12345',
      channelManager: 'https://channel.manager/app/reservation/booking-001',
      paymentLink: 'https://pay.customer-automator.com/invoice/booking-001',
    },
  },
  {
    id: 'booking-002',
    reference: 'Prenotazione n°5',
    guestId: 'guest-francesca-gallo',
    guestName: 'Francesca Gallo',
    stayPeriod: '14 Feb → 17 Feb 2025',
    nights: 3,
    adults: 2,
    children: 0,
    status: 'confermato',
    channel: 'diretta',
    packageName: 'Romantic Escape Deluxe',
    outstandingBalance: 0,
    aiConfidence: 0.95,
    roomType: 'Penthouse Luna',
    aiInsights: [
      'Proporre esperienza “Chef Table” il sabato sera.',
      'Inviare messaggio personalizzato tramite concierge digitale la mattina dell’arrivo.',
    ],
    automation: [
      {
        id: 'step-01',
        label: 'Prenotazione confermata',
        description: 'Email di conferma con voucher digitale',
        channel: 'email',
        status: 'completato',
        scheduledAt: '12/01/2025 10:15',
        completedAt: '12/01/2025 10:15',
      },
      {
        id: 'step-02',
        label: 'Suggerimenti romantici',
        description: 'WhatsApp con proposte personalizzate',
        channel: 'whatsapp',
        status: 'completato',
        scheduledAt: '12/02/2025 18:00',
        completedAt: '12/02/2025 18:02',
      },
      {
        id: 'step-03',
        label: 'Check-in online',
        description: 'Richiesta documenti e preferenze arrivo',
        channel: 'email',
        status: 'in_attesa',
        scheduledAt: '07/02/2025 09:00',
      },
      {
        id: 'step-04',
        label: 'Gift finale',
        description: 'Promemoria manuale per consegna box gourmet',
        channel: 'email',
        status: 'manuale',
        scheduledAt: '17/02/2025 12:00',
      },
    ],
    sensors: [
      {
        id: 'lighting-penthouse',
        name: 'Luci sceniche',
        icon: 'sun',
        value: 'Scena tramonto',
        status: 'ok',
        lastUpdate: '10 min fa',
        actionable: true,
        actions: ['Attiva scena relax', 'Attiva scena romantica'],
      },
      {
        id: 'wellness-penthouse',
        name: 'Spa privata',
        icon: 'spa',
        value: 'Preriscaldo 32°C',
        status: 'ok',
        lastUpdate: 'In tempo reale',
        actionable: true,
        actions: ['Avvia idromassaggio', 'Invia aroma relax'],
      },
    ],
    tags: ['vip', 'romantico', 'chef-table'],
    createdAt: '12/01/2025',
    externalReferences: {
      channelManager: 'https://channel.manager/app/reservation/booking-002',
      paymentLink: 'https://pay.customer-automator.com/invoice/booking-002',
    },
  },
];

export const newsletterSubscribers: NewsletterSubscriber[] = [
  {
    id: 'newsletter-001',
    guestName: 'Giovanni Greco',
    guestId: 'guest-giovanni-greco',
    email: 'giovanni.greco@example.com',
    status: 'attivo',
    topics: ['Experience', 'Eventi famiglie', 'Promo spa'],
    lastInteraction: '05/11/2024',
  },
  {
    id: 'newsletter-002',
    guestName: 'Antonio Marino',
    guestId: 'guest-antonio-marino',
    email: 'antonio.marino@example.com',
    status: 'sospeso',
    topics: ['Business lounge', 'Upgrade camere'],
    lastInteraction: '21/09/2024',
  },
  {
    id: 'newsletter-003',
    guestName: 'Francesca Gallo',
    guestId: 'guest-francesca-gallo',
    email: 'francesca.gallo@example.com',
    status: 'attivo',
    topics: ['Chef Table', 'Esperienze gourmet', 'Spa privata'],
    lastInteraction: '04/01/2025',
  },
];

export const templates: Template[] = [
  {
    id: 'template-pre-arrivo',
    name: 'Benvenuto in struttura',
    description:
      'Presentazione dell’hotel, credenziali Wi-Fi, mappa interattiva e concierge digitale.',
    category: 'pre_arrivo',
    lastUpdate: '03/02/2025',
    performance: {
      openRate: 0.86,
      clickRate: 0.62,
      conversionRate: 0.48,
    },
    variables: ['guest.firstname', 'booking.arrivalDate', 'portal.link'],
    preview:
      'Ciao {{guest.firstname}}, la tua esperienza inizia qui. Accedi al concierge digitale per personalizzare il soggiorno.',
  },
  {
    id: 'template-upsell-spa',
    name: 'Momento di relax',
    description: 'Proposta di upgrade spa con slot dinamici.',
    category: 'upselling',
    lastUpdate: '17/01/2025',
    performance: {
      openRate: 0.74,
      clickRate: 0.41,
      conversionRate: 0.29,
    },
    variables: ['spa.availableSlots', 'guest.preference.spa'],
    preview:
      'Abbiamo riservato per te un percorso benessere. Scegli l’orario che preferisci e aggiungi un massaggio esclusivo.',
  },
  {
    id: 'template-post-stay',
    name: 'Grazie del soggiorno',
    description: 'Email post soggiorno con richiesta recensione e membership.',
    category: 'post_soggiorno',
    lastUpdate: '28/12/2024',
    performance: {
      openRate: 0.67,
      clickRate: 0.38,
      conversionRate: 0.18,
    },
    variables: ['review.link', 'loyalty.discountCode'],
    preview:
      'È stato un piacere averti con noi. Raccontaci come è andata e scopri la sorpresa riservata per il tuo prossimo viaggio.',
  },
];

export const inboxMessages: InboxMessage[] = [
  {
    id: 'msg-001',
    guestName: 'Giovanni Greco',
    guestId: 'guest-giovanni-greco',
    bookingId: 'booking-001',
    channel: 'whatsapp',
    receivedAt: '10:12',
    summary: 'Possiamo anticipare l’accesso alla camera di un’ora? I bambini arrivano presto.',
    unread: true,
    aiSuggestedReply:
      'Certo Giovanni, posso attivare il servizio early check-in con un supplemento di €25. Confermi?',
    urgency: 'media',
    context: 'Ultimo messaggio del 10:12, pagamento ancora in sospeso.',
  },
  {
    id: 'msg-002',
    guestName: 'Francesca Gallo',
    guestId: 'guest-francesca-gallo',
    bookingId: 'booking-002',
    channel: 'email',
    receivedAt: '09:45',
    summary: 'Vorrei prenotare una cena speciale sabato, avete proposte? Vorrei qualcosa di scenografico.',
    unread: false,
    aiSuggestedReply:
      'Francesca, possiamo riservarti la Chef Table con percorso degustazione a €180 a persona. Vuoi che confermi per le 20:30?',
    urgency: 'alta',
    context: 'Ultima interazione positiva, cliente con punteggio loyalty elevato.',
  },
  {
    id: 'msg-003',
    guestName: 'Davide Nardi',
    guestId: 'guest-davide-nardi',
    channel: 'booking',
    receivedAt: 'Ieri',
    summary: 'Codice Wi-Fi non funziona. Potete inviarne uno nuovo?',
    unread: true,
    aiSuggestedReply:
      'Ti invio un nuovo accesso Wi-Fi valido fino al check-out. Conferma se ora riesci a connetterti.',
    urgency: 'media',
    context: 'Conversazione spostata dal chatbot all’operatore per verifica credenziali.',
  },
];

export const guestPortalSections: GuestPortalSection[] = [
  {
    id: 'dashboard',
    title: 'Home soggiorno',
    description:
      'Panoramica con countdown all’arrivo, suggerimenti dinamici e stato delle richieste.',
    items: ['Countdown arrivo', 'Link rapidi concierge', 'Stato richieste IoT'],
  },
  {
    id: 'services',
    title: 'Servizi e prenotazioni',
    description:
      'Catalogo dinamico per spa, ristorante, escursioni, con tempi di risposta in tempo reale.',
    items: ['Prenota spa', 'Prenota ristorante', 'Tour locale'],
  },
  {
    id: 'chat',
    title: 'Chat assistita',
    description:
      'Conversazione unica per email, WhatsApp e portale con suggerimenti AI e traduzione live.',
    items: ['Risposte rapide', 'Suggerimenti AI', 'Trascrizione vocale'],
  },
  {
    id: 'documents',
    title: 'Documenti e fatture',
    description: 'Archivio digitale sempre accessibile per ricevute, voucher e photo memories.',
    items: ['Fattura digitale', 'Voucher attività', 'Gallery soggiorno'],
  },
];

